version: "3"
services:
  muvel:
    ports:
      - "127.0.0.1:1338:2556"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres
    ports:
      - "2345:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=paring
      - POSTGRES_DB=muvel
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    volumes:
      - meili_data:/meili_data
    ports:
      - "7700:7700"
    restart: unless-stopped

volumes:
  pg-data:
  meili_data:
