version: "3"
services:
  muvel:
    ports:
      - "127.0.0.1:1338:3000"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always

  db:
    image: postgres
    ports:
      - "2345:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=paring
      - POSTGRES_DB=muvel

volumes:
  pg-data:
