[package]
name = "muvel"
version = "2.3.1"
description = "Web-Novel Editor"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.2.0", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.5.0", features = ["devtools"] }
tauri-plugin-log = "2.0.0-rc"
tauri-plugin-opener = "2"
tauri-plugin-deep-link = "2"
url = "2.5.4"
tiny_http = "0.12.0"
uuid = { version = "1.16.0", features = ["v4"] }
chrono = "0.4.41"
tauri-plugin-dialog = "2.2.1"
serde_repr = "0.1.20"
slug = "0.1.6"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
font-kit = "0.11"
tauri-plugin-cli = "2"
tauri-plugin-updater = "2"
